// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeGiMn7lFZht8EvAL3YVF96Cgzj8Xfff0',
    appId: '1:363578063054:web:20074cbf39da440be3f89f',
    messagingSenderId: '363578063054',
    projectId: 'shakawa-7cda7',
    authDomain: 'shakawa-7cda7.firebaseapp.com',
    storageBucket: 'shakawa-7cda7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtFhXpI7FBdkew0tcT3Br8667Yr_6mrWg',
    appId: '1:363578063054:android:797a361c459885dee3f89f',
    messagingSenderId: '363578063054',
    projectId: 'shakawa-7cda7',
    storageBucket: 'shakawa-7cda7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARseImSDlRncMmam7zyVJH-CqJ1lfLAS0',
    appId: '1:363578063054:ios:7bdb31091ec6e0dae3f89f',
    messagingSenderId: '363578063054',
    projectId: 'shakawa-7cda7',
    storageBucket: 'shakawa-7cda7.firebasestorage.app',
    androidClientId: '363578063054-ne3t2f3u1hujfmt22srghuhho5s2ug4s.apps.googleusercontent.com',
    iosClientId: '363578063054-lpif3a35r5aua096f72mu66d908p9kqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARseImSDlRncMmam7zyVJH-CqJ1lfLAS0',
    appId: '1:363578063054:ios:7bdb31091ec6e0dae3f89f',
    messagingSenderId: '363578063054',
    projectId: 'shakawa-7cda7',
    storageBucket: 'shakawa-7cda7.firebasestorage.app',
    androidClientId: '363578063054-ne3t2f3u1hujfmt22srghuhho5s2ug4s.apps.googleusercontent.com',
    iosClientId: '363578063054-lpif3a35r5aua096f72mu66d908p9kqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeGiMn7lFZht8EvAL3YVF96Cgzj8Xfff0',
    appId: '1:363578063054:web:aed7e2f59332aabde3f89f',
    messagingSenderId: '363578063054',
    projectId: 'shakawa-7cda7',
    authDomain: 'shakawa-7cda7.firebaseapp.com',
    storageBucket: 'shakawa-7cda7.firebasestorage.app',
  );
}
