name: Production Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./shakawa_front
        run: flutter pub get

      - name: Build Windows
        working-directory: ./shakawa_front
        run: flutter build windows --release

      - name: Release Windows App
        uses: softprops/action-gh-release@v1
        with:
          files: shakawa_front/build/windows/x64/runner/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}